name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Qarc.DataFeed
          file: ./Qarc.DataFeed/Qarc.DataFeed.Adapter.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/quantarcanum:qarc-datafeed

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG_BASE64 }}
      - run: kubectl delete -f ./Qarc.DataFeed/Kubernetes/deployment.yaml --ignore-not-found=true
      - run: kubectl delete -f ./Qarc.DataFeed/Kubernetes/service.yaml --ignore-not-found=true
      - run: kubectl delete -f ./Qarc.DataFeed/Kubernetes/ingressroute.yaml --ignore-not-found=true
      - run: kubectl create -f ./Qarc.DataFeed/Kubernetes/deployment.yaml
      - run: kubectl create -f ./Qarc.DataFeed/Kubernetes/service.yaml
      - run: kubectl create -f ./Qarc.DataFeed/Kubernetes/ingressroute.yaml
